name: donation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
     # ✅ TAMBAHKAN INI untuk localization
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  lottie: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.2

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  image_picker: ^1.0.4

  # Animations
  animate_do: ^4.2.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
   # ✅ ENABLE INTERNATIONALIZATION
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf
